#_______ ANALYSIS STEPS _________________________________________________________#

steps:
# - mapping
# - assembly
# - structural_variant_calling
# - variant_calling
# - cDNA_pinfish
# - cDNA_expression
# - expression_analysis
# - cDNA_stringtie
# - cDNA_flair
# - repeat_expansion (TODO)
  - qc
  - qc_db

#_______ REFERENCE FILES _________________________________________________________#

ref:
  genome: "/mnt/storage1/share/data/genomes/GRCh38.fa"
  #annotation: "/mnt/SRV018/users/ahgrosc1/data/Homo_sapiens.GRCh38.85.chr.gtf"
  annotation: "/mnt/storage1/users/ahgrosc1/data/gencode.v34.annotation.gtf"
  annotation_bed: "/mnt/storage1/users/ahgrosc1/data/gencode.v34.annotation.bed"
  cDNA: "/mnt/SRV018/users/ahgrosc1/data/Homo_sapiens.GRCh38.cdna.all.fa"
  target_region: "/mnt/storage1/users/ahgrosc1/data/WGS_grch38.bed"
  vc_benchmark: "/mnt/storage1/users/ahgrosc1/data/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_PGandRTGphasetransfer.vcf.gz"
  vc_confidence_region: "/mnt/storage1/users/ahgrosc1/data/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_nosomaticdel_noCENorHET7.bed"


#_______ SYSTEM SETTINGS _________________________________________________________#

sample_file: "sample_run_table.tsv"
project_config: "config.yml"
use_gpu: true
gpu_id: "GPU-2c38ecef-c1ce-d516-ebb9-2b381cf15f21"

prom:
  ssh_profile: "microbio"
  data_folder: "/mnt/promdata"

use_failed_reads: false
transfer_fast5: true

sys:
  max_threads: 12

apps:
  multiqc: "/mnt/users/ahgrosc1/tools/bin/multiqc"
  qualimap: "unset DISPLAY; /mnt/storage1/users/ahgrosc1/tools/qualimap/qualimap" 
  stringtie: "/mnt/storage1/users/ahgrosc1/tools/stringtie/stringtie"
  sqanti: "python /mnt/storage1/users/ahgrosc1/tools/SQANTI3/sqanti3_qc.py"
  cdna_cupcake: "/mnt/storage1/users/ahgrosc1/tools/cDNA_Cupcake/" # Enter root folder

verbose: false  # Prints samples, barcode and folder informations
skip_name_check: false # Dont check run folder names for correct formatq

#______ ANALYSIS PARAMETERS _______________________________________________________#

assembly:
  methods: 
    - "wtdbg"
    - "flye"
  genome_size: "3G"

transcript:
  # Minimap2 mapping options
  minimap2_opts: ""
  # Maximum secondary alignments
  maximum_secondary: 100
  # Secondary score ratio (-p for minimap2)
  secondary_score_ratio: 1.0

mapping:
  #Min mapping quality filter (Full_length splice)
  min_qual: 20

#_____ VARIANT CALLING PARAMETERS _______________________________________________#

vc:
  medaka: false 
  pepper: true
  clair3: false
  phased_output: true     # Generate phased variant calling output (Supported in Pepper and Clair3)
  create_benchmark: false #TODO Check if this works
  keep_supplementary: false


vc_clair3:
  model: "r941_prom_sup_g5014"

vc_medaka:
  model_initial: "r941_prom_snp_g303" #Depends on flowcell and guppy version
  model_final: "r941_prom_high_g303" #Depends on flowcell and guppy version

vc_pepper:
  model: "ont_r9_guppy5_sup"
  target_region: false    # Restrict variant calling / phasing to target region

sv_cutesv:
  enable_genotyping: true 

#______ QC PARAMETERS ____________________________________________________________#

gffcompare:
  options: "-R -Q" # Ignore transcript found only in ref oder only in query

#______ RUN QC DATABASE ___________________________________________________________#

run_db_root: "/mnt/share/data/ont_run_qc"

#______ FLAIR PARAMETERS _________________________________________________________#

flair:
  manifest: "reads_manifest.tsv"
  trust_ends: yes   # Use this option if using long unfragmented reads, e.g. preprocessed with pychopper
  min_qual: 1

#______ EXPRESSION PARAMETERS ___________________________________________________#

expression:
  level: "exon"
  min_qual: 3
  strandedness: 1 # 0:unstranded 1:stranded 2:reversely stranded
  # Maximum secondary alignments
  maximum_secondary: 100
  # Secondary score ratio (-p for minimap2)
  secondary_score_ratio: 1.0
  # Salmon library type
  salmon_libtype: "U"

#______ DUAL BARCODING DEMULTIPLEX ______________________________________________#

demux:
  bc_index: 'bc_index_file.csv'
  bc_distance: 3
  minibar: '/mnt/users/ahgrosc1/tools/miniconda3/bin/python /mnt/users/ahgrosc1/tools/minibar/minibar.py'
  target_region: 'testbla'
  target_region_str: 'chr1:155232501-155241415'