ref:
  genome: "/mnt/share/data/genomes/GRCh38.fa"
  transcript_annotation: "resources/Homo_sapiens.GRCh38.85.gtf"
  transcript_cDNA: "resources/Homo_sapiens.GRCh38.cdna.all.fa"

sample_file: "sample_run_table.tsv"

prom:
  ssh_profile: "microbio"
  data_folder: "/mnt/promdata"

use_failed_reads: false
transfer_fast5: true

apps:
    multiqc: "/mnt/users/ahgrosc1/tools/MultiQC/venv/bin/multiqc"
