# Conventions: 
# - All options are lowercase
# - Words separated by underscores

#_______ ANALYSIS STEPS _________________________________________________________#

steps:
# - mapping
# - fastq
# - assembly
# - structural_variant_calling
# - variant_calling
# - cdna
# - transcriptome
# - gene_expression
# - differential_transcript_usage
# - modbases
# - cnv
# - local_assembly
  - qc
  - qc_db

#_______ REFERENCE FILES _________________________________________________________#

ref:
  genome: "/mnt/storage1/share/data/genomes/GRCh38.fa"
  annotation: "/mnt/storage3/users/ahgrosc1/data/gencode.v34.annotation.gtf"
  annotation_bed: "/mnt/storage3/users/ahgrosc1/data/gencode.v34.annotation.bed"
  cDNA: "/mnt/storage3/users/ahgrosc1/data/Homo_sapiens.GRCh38.cdna.all.fa"
  target_region: "/mnt/storage3/users/ahgrosc1/data/WGS_grch38.bed"
  core_genome: "/mnt/storage3/users/ahgrosc1/data/WGS_grch38.bed"

#_______ SYSTEM SETTINGS _________________________________________________________#

# Filenames
sample_file: "sample_run_table.tsv"
project_config: "config.yml"

verbose: false                      # Prints samples, barcode and folder informations
skip_name_check: false              # Dont check run folder names for correct format

# GPU Settings (for Pepper-Margin-Deepvariant and Basecalling)
use_gpu: true
gpu_id:
  id: "GPU-2c38ecef-c1ce-d516-ebb9-2b381cf15f21"
  cuda: "cuda:0"

max_threads: 40                     # Max threads for individual jobs

# Links to executables
apps:
  sqanti: "python /mnt/storage3/users/ahgrosc1/tools/sqanti3/SQANTI3-5.1.1/sqanti3_qc.py"
  guppy: "/mnt/storage3/users/ahgrosc1/tools/guppy/ont-guppy_6.4.6/bin/guppy_basecaller"

#______ ANALYSIS PARAMETERS ______________________________________________________#

fastq_prefer_rebasecalled: false     # If exists, take only fastq in folder `fastq_rebasecalled`
use_failed_reads: false             # Include `failed_reads` with Q<7

mapping:
  min_qual: 20                      # Min mapping quality filter (Full_length splice)

#_____ BASECALLING _______________________________________________________________#
basecaller: "bonito"                # Available: "bonito", "guppy"

bonito:
  model: "dna_r9.4.1_e8_hac@v3.3"   # bonito download --models --show
  modified_bases: "5mC"

guppy:
  model: "dna_r9.4.1_450bps_modbases_5mc_cg_hac_prom.cfg"      # View available with guppy_basecaller --print_workflows
  min_qscore: 7

map_during_basecalling: true
# Currently only HSISDM in Cigar String available, no X/=
# For both mapping in bonito an guppy

use_mod_bam: false                  # use modbases bam for variant calling?

#_____ STRUCTURAL VARIANT CALLING PARAMETERS _____________________________________#

sv:
  sniffles: true
  cutesv: true
  dipdiff: false

#_____ VARIANT CALLING PARAMETERS ________________________________________________#

vc:
  pepper: true
  clair3: false
  deepvariant: false
  phased_output: true               # Generate bamfile phased reads (Clair3)
  haplotagged_bam: true             # Generate bamfile phased reads (Pepper-M-DV)
  keep_supplementary: false

vc_clair3:
  model: "r941_prom_hac_g360+g422"      # https://github.com/HKU-BAL/Clair3#pre-trained-models

vc_pepper:
  model: "ont_r9_guppy5_sup"        # Model
  target_region: false              # Restrict variant calling / phasing to target region (chr1:1234-12345)

sv_cutesv:
  enable_genotyping: true 

#______ ASSEMBLY PARAMETERS ______________________________________________________#

assembly:
  methods: 
    - "flye"
#   - "wtdbg"
#   - "metaflye"
  genome_size: "3G"
  max_target_coverage: false        # Subsample reads (not needed for current flye)
  max_flye_cov: 70                  # for SUP reads and R10. Old data: --nano-raw


#_______ CDNA ANALYSIS ___________________________________________________________#

cdna:
  with_umi: false
  primer_kit: "PCS109"
  deduplicate: false

#_______ TRANSCRIPTOME ANALYSIS __________________________________________________#

transcriptome:
  methods:
    - "stringtie"
#   - "flair"

flair:
  manifest: "reads_manifest.tsv"
  trust_ends: yes                   # Use if preprocessed with pychopper
  min_qual: 1

gffcompare:
  options: "-R -Q"                  # Ignore transcript found only in ref oder only in query

#_______ CNVKIT __________________________________________________________________#
# Params not optimized for Tumor samples yet.

cnvkit:
  reference: ""
  reference_samples:
    21073LRa080: /mnt/storage1/projects/research/21073N_SEQ418081722_mitopathy/Sample_21073LRa080/21073LRa080.bam
    21073LRa086: /mnt/storage1/projects/research/21073N_SEQ418081722_mitopathy/Sample_21073LRa086/21073LRa086.bam
    21073LRa076: /mnt/storage1/projects/research/21073N_SEQ418081722_mitopathy/Sample_21073LRa076/21073LRa076.bam
    21073LRa101: /mnt/storage1/projects/research/21073N_SEQ418081722_mitopathy/Sample_21073LRa101/21073LRa101.bam
  binsize: 15000
  minbinsize: 100
  mingapsize: 5000
  include_region: "/mnt/storage3/users/ahgrosc1/data/WGS_grch38.bed"
  exclude_region: "/mnt/storage3/users/ahgrosc1/data/cnvkit_ref/GRCh38/sv_blacklist.bed"
  segment_method: "cbs"           # methods: cbs, haar, hmm, hmm-tumor, hmm-germline, none

  call:
    center: "mode"                # options: mean, median, mode. biweight
    method: "clonal"              # methods: threshold, clonal, none
    ploidy: 2

  scatter:
    color: "red"
    ymax: 5
    ymin: -5
    region: "all"                 # Plot zoom on target regions Allowed formats: chr1_1233-12314 (win compatible) or chr1:123154-234235 (unix)

#______ LOCAL ASSEMBLY ___________________________________________________________#

local_assembly:
  regions:                        # Default: No local assembly regions defined
    - ""                          # Allowed formats: chr1_1233-12314 (win compatible) or chr1:123154-234235 (unix)
  haplotypes:                     # Separates local assembly with the selected haplotypes
    - ""                          # Default: All reads are used, no haplotype filtering
  # - 1
  # - 2

#______ QC PARAMETERS ____________________________________________________________#

qualimap:
  target: false

#______ RUN QC DATABASE __________________________________________________________#

run_db_root: "/mnt/share/data/ont_run_qc"
report_filetypes:
  - md
  - html
  - json
disable_sampleqc: false

#______ GENE/TRANSCRIPT EXPRESSION SETTINGS ______________________________________#

transcript:
  map_to_custom_annot: true       # Use novel annot from Stringtie/Flair for Mapping
  minimap2_opts: ""               # Minimap2 mapping options
  maximum_secondary: 100          # Maximum secondary alignments
  secondary_score_ratio: 1.0      # Same as -p  option in minimap2

expression:
  level: "exon"
  min_qual: 3
  strandedness: 1                 # 0:unstranded 1:stranded 2:reversely stranded
  salmon_libtype: "SR"             # U = unspecific, S = strand-specific

#______ DUAL BARCODING DEMULTIPLEX _______________________________________________#

demux:
  bc_index: 'bc_index_file.csv'
  bc_distance: 3
  minibar: '/mnt/storage3/users/ahgrosc1/tools/miniconda3/bin/python /mnt/storage3/susers/ahgrosc1/tools/minibar/minibar.py'
  target_region: ''
  target_region_str: ''