ref:
  genome: "/mnt/share/data/genomes/GRCh38.fa"

sample_file: "sample_run_table.tsv"

prom:
  ssh_profile: "microbio"
  data_folder: "/mnt/promdata"

use_failed_reads: false
transfer_fast5: true

# Remove unwanted analysis steps
steps:
  - mapping
  - assembly
  - cDNA
  - qc

assembly:
  methods: 
    - "wtdbg"
#   - "flye"
  genome_size: "3G"
  quast_conf:
    eukaryote: true 


transcript:
  transcript_annotation: "resources/Homo_sapiens.GRCh38.85.gtf"
  transcript_cDNA: "resources/Homo_sapiens.GRCh38.cdna.all.fa"

sys:
  max_threads: 12

apps:
  multiqc: "/mnt/users/ahgrosc1/tools/MultiQC/venv/bin/multiqc"
