#_______ ANALYSIS STEPS _________________________________________________________#

steps:
  - mapping
# - assembly
# - structural_variant_calling (TODO)
# - variant_calling (TODO)
# - cDNA
  - pinfish_annotation
  - qc

#_______ REFERENCE FILES _________________________________________________________#

ref:
  genome: "/mnt/share/data/genomes/GRCh38.fa"
  annotation: "/mnt/SRV018/users/ahgrosc1/data/Homo_sapiens.GRCh38.85.chr.gtf"
  cDNA: "/mnt/SRV018/users/ahgrosc1/data/Homo_sapiens.GRCh38.cdna.all.fa"

#_______ SYSTEM SETTINGS _________________________________________________________#

sample_file: "sample_run_table.tsv"

prom:
  ssh_profile: "microbio"
  data_folder: "/mnt/promdata"

use_failed_reads: false
transfer_fast5: true

sys:
  max_threads: 12

apps:
  multiqc: "/mnt/SRV018/users/ahgrosc1/tools/MultiQC/venv/bin/multiqc"
  qualimap: "unset DISPLAY; /mnt/SRV018/users/ahgrosc1/tools/qualimap/qualimap" 
  stringtie: "/mnnt/SRV018/users/ahgrosc1/tools/stringtie/stringtie"

#______ ANALYSIS PARAMETERS _______________________________________________________#

assembly:
  methods: 
    - "wtdbg"
    - "flye"
  genome_size: "3G"

transcript:
  # Minimap2 mapping options
  minimap2_opts: ""

  # Maximum secondary alignments
  maximum_secondary: 100

  # Secondary score ratio (-p for minimap2)
  secondary_score_ratio: 1.0


mapping:
  #Min mapping quality filter (Full_length splice)
  min_qual: 20


#### PINFISH 
pinfish:
  minimap2_opts: "-uf" # Find canonical splicing sites on f: transcript strand
  minimum_mapping_quality: 10
  spliced_bam2gff_opts: "-s"
  minimum_cluster_size: 10
  minimum_isoform_percent: 1.0
  exon_boundary_tolerance: 10
  terminal_exon_boundary_tolerance: 30
  minimap2_opts_polished: "-uf"
  spliced_bam2gff_opts_pol: "-s"
  # Options passed to collapse_partials when collapsing fragmentation artifacts
  # in clustered and polished transcripts.
  collapse_internal_tol: 5  #Internal exon boundary tolerance for collapsing
  collapse_five_tol: 5000   # Five prime boundary tolerance for collapsing
  collapse_three_tol: 30 # Three prime boundary tolerance for collapsing

