#_______ ANALYSIS STEPS _________________________________________________________#

steps:
# - mapping
# - fastq
# - assembly
# - structural_variant_calling
# - variant_calling
# - cDNA_expression
# - cDNA_stringtie
# - cDNA_flair
# - modbases
# - cnv
# - local_assembly
  - qc
  - qc_db

#_______ REFERENCE FILES _________________________________________________________#

ref:
  genome: "/mnt/storage1/share/data/genomes/GRCh38.fa"
  annotation: "/mnt/storage1/users/ahgrosc1/data/gencode.v34.annotation.gtf"
  annotation_bed: "/mnt/storage1/users/ahgrosc1/data/gencode.v34.annotation.bed"
  cDNA: "/mnt/SRV018/users/ahgrosc1/data/Homo_sapiens.GRCh38.cdna.all.fa"
  target_region: "/mnt/storage1/users/ahgrosc1/data/WGS_grch38.bed"

#_______ SYSTEM SETTINGS _________________________________________________________#

# Filenames
sample_file: "sample_run_table.tsv"
project_config: "config.yml"

# Prints samples, barcode and folder informations
verbose: false 
# Dont check run folder names for correct format
skip_name_check: false 

# GPU Settings (for Pepper-Margin-Deepvariant)
use_gpu: true
gpu_id:
  id: "GPU-2c38ecef-c1ce-d516-ebb9-2b381cf15f21"
  cuda: "cuda:0"

# Max threads per process
max_threads: 40

# Links to executables
apps:
  sqanti: "python /mnt/storage1/users/ahgrosc1/tools/SQANTI3/sqanti3_qc.py"

#______ ANALYSIS PARAMETERS _____________________________________________________#

# Take raw fastq only from folder with name `fastq_rebasecalled` if existing
fastq_prefer_rebasecalled: true
use_failed_reads: false

mapping:
  #Min mapping quality filter (Full_length splice)
  min_qual: 20

#_____ STRUCTURAL VARIANT CALLING PARAMETERS _____________________________________#

sv:
  sniffles: true
  cutesv: true
  dipdiff: false

#_____ VARIANT CALLING PARAMETERS _______________________________________________#

vc:
  pepper: true
  clair3: false
  phased_output: true  # Generate phased reads 
  haplotagged_bam: true
  keep_supplementary: false

vc_clair3:
  model: "r941_prom_sup_g5014"

vc_pepper:
  model: "ont_r9_guppy5_sup"
  target_region: false    # Restrict variant calling / phasing to target region

sv_cutesv:
  enable_genotyping: true 

#_____ BASE MODIFICATIONS _______________________________________________________#

# Settings for bonito (mod)basecalling
bonito:
  model: "dna_r9.4.1_e8_hac@v3.3"
  modified_bases: "5mC"

# Should modbases bam from bonito be used for variant calling?
use_mod_bam: false

#______ ASSEMBLY PARAMETERS ______________________________________________________#

assembly:
  methods: 
    - "flye"
#   - "wtdbg"
#   - "metaflye"
  genome_size: "3G"

#_______ CNVKIT __________________________________________________________________#

# Params not optimized for Tumor samples yet.
cnvkit:
  reference: ""
  reference_samples:
    21073LRa080: /mnt/storage1/projects/research/21073N_SEQ418081722_mitopathy/Sample_21073LRa080/21073LRa080.bam
    21073LRa086: /mnt/storage1/projects/research/21073N_SEQ418081722_mitopathy/Sample_21073LRa086/21073LRa086.bam
    21073LRa076: /mnt/storage1/projects/research/21073N_SEQ418081722_mitopathy/Sample_21073LRa076/21073LRa076.bam
    21073LRa101: /mnt/storage1/projects/research/21073N_SEQ418081722_mitopathy/Sample_21073LRa101/21073LRa101.bam
  binsize: 15000
  minbinsize: 100
  mingapsize: 5000
  targets: "/mnt/users/ahgrosc1/data/WGS_grch38.bed"
  exclude_region: "/mnt/users/ahgrosc1/data/cnvkit_ref/sv_blacklist.bed"
  segment_method: "cbs"
  # available methods: cbs, haar, hmm, hmm-tumor, hmm-germline, none

  call:
    center: "mode"
    # available options: mean, median, mode. biweight
    method: "clonal"
    # available methods: threshold, clonal, none
    ploidy: 2

  scatter:
    color: "red"
    ymax: 5
    ymin: -5
    region:

#______ LOCAL ASSEMBLY ___________________________________________________________#

local_assembly:
  regions:
    - ""

#______ REPEAT EXPANSIONS ____________________________________________________________#

repeat_expansion:
  trgt: "path"
  trvz: "path"
  loci: "bed"



#______ QC PARAMETERS ____________________________________________________________#

gffcompare:
  options: "-R -Q" # Ignore transcript found only in ref oder only in query

qualimap:
  target: false

#______ RUN QC DATABASE ___________________________________________________________#

run_db_root: "/mnt/share/data/ont_run_qc"
report_filetypes:
  - md
  - html
  - json

#______ TRANSCRIPTOME ANALYSIS (FLAIR) PARAMETERS _________________________________#

flair:
  manifest: "reads_manifest.tsv"
  trust_ends: yes   # Use this option if using long unfragmented reads, e.g. preprocessed with pychopper
  min_qual: 1

#______ TRANSCRIPT EXPRESSION PARAMETERS __________________________________________#

transcript:
  # Minimap2 mapping options
  minimap2_opts: ""
  # Maximum secondary alignments
  maximum_secondary: 100
  # Secondary score ratio (-p for minimap2)
  secondary_score_ratio: 1.0

expression:
  level: "exon"
  min_qual: 3
  strandedness: 1 # 0:unstranded 1:stranded 2:reversely stranded
  # Salmon library type
  salmon_libtype: "S"  # U = unspecific, S = strand-specific

#______ DUAL BARCODING DEMULTIPLEX ______________________________________________#

demux:
  bc_index: 'bc_index_file.csv'
  bc_distance: 3
  minibar: '/mnt/users/ahgrosc1/tools/miniconda3/bin/python /mnt/users/ahgrosc1/tools/minibar/minibar.py'
  target_region: ''
  target_region_str: ''