custom_logo: '../resources/logo_ncct.png'
custom_logo_url: 'https://portal.qbic.uni-tuebingen.de/portal/web/ncct/our-center'
custom_logo_title: 'NCCT Tübingen'

extra_fn_clean_exts:
    - '.pycoQC.json'

extra_fn_clean_trim:
    - '_stats'      # Pychopper output
    - '_genome'     # QualiMap BAMQC folder
    - '_var'        # BCFtools stats
    - '.spliced'    # featureCounts
    - '.asm.wtdbg'  # Assembly
    - '.asm.flye'   # Assembly

run_modules:
  - readqc
  - pychopper
  - mappingqc
  - gffcompare
  - rseqc
  - qualimap
  - quast
  - mosdepth
  - featureCounts
  - custom_content
  - pycoqc

skip_generalstats: false

table_columns_visible:
  QualiMap:
    avg_gc: false
    general_error_rate: true
    mean_coverage: false
    5_x_pc: true
  