custom_logo: '../resources/logo_ncct.png'
custom_logo_url: 'https://portal.qbic.uni-tuebingen.de/portal/web/ncct/our-center'
custom_logo_title: 'NCCT Tübingen'

extra_fn_clean_exts:
    - '.pycoQC.json'
    